services:
  nfsuserver:
    image: ghcr.io/the-may/nfsuserver:latest
    container_name: nfsuserver
    restart: unless-stopped
    network_mode: "host"
#    ports:
#      - "10900:10900/tcp"
#      - "10901:10901/tcp"
#      - "10980:10980/tcp"
#      - "10800:10800/tcp"
#      - "10800:10800/udp"
#      - "3658-3659:3658-3659/tcp"

    volumes:
      - ./config/nfsu.conf:/opt/nfsuserver/nfsu.conf:ro
      - ./config/news.txt:/opt/nfsuserver/news.txt:ro

  php:
    image: php:8.2-fpm-alpine
    container_name: nfsu-php
    restart: unless-stopped
    volumes:
      - ./web:/var/www/html

  web:
    image: nginx:alpine
    container_name: nfsu-web
    restart: unless-stopped
    depends_on:
      - php
    ports:
      - "10780:80"
    volumes:
      - ./web:/var/www/html
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf:ro
